application:
  errors:
    # Common Error Code Configuration
    internal_server_error:
      code: 500
      message: Internal server error
    data_access_exception:
      code: 501
      message: Database is down or not available
    # Person-Service Error Code Configuration

    person_not_found:
      code: PERSON_NOT_FOUND
      message: Person with personId {0} not found
    # Asset-Service Error Code Configuration
    asset_not_found:
      code: ASSET_NOT_FOUND
      message: Asset with assetId {0} not found
    # Address-Service Error Code Configuration
    address_not_found:
      code: ADDRESS_NOT_FOUND
      message: Address with addressId {0} not found
    # Account-Service Error Code Configuration
    account_not_found:
      code: ACCOUNT_NOT_FOUND
      message: Address with accountId {0} not found
