server:
  port: ${ACCOUNT_SERVICE_PORT:8080}
  servlet:
    context-path: /account-service
spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/h2/account_db
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
        