server:
  port: ${ACCOUNT_SERVICE_PORT:8082}
  servlet:
    context-path: /account-service
spring:
  profiles:
    include:
      - common
    active: dev
---
spring:
  profiles: dev
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:account_db_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles: uat
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:account_db_uat
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles: prod
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:account_db_prod
    username: sa
    password:
    driver-class-name: org.h2.Driver
