server:
  port: ${ADDRESS_SERVICE_PORT:8083}
  servlet:
    context-path: /address-service
spring:
  profiles:
    include:
      - common
    active: dev
---
spring:
  profiles: dev
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:E:/workspaces/Gitxi2852Projects/person-management-system/h2/address_db_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles: uat
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:E:/workspaces/Gitxi2852Projects/person-management-system/h2/address_db_uat
    username: sa
    password:
    driver-class-name: org.h2.Driver
---
spring:
  profiles: prod
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:E:/workspaces/Gitxi2852Projects/person-management-system/h2/address_db_prod
    username: sa
    password:
    driver-class-name: org.h2.Driver
