server:
  port: ${ASSET_SERVICE_PORT:8084}
  servlet:
    context-path: /asset-service
spring:
  profiles:
    include:
      - common
    active: dev
---
spring:
  profiles: dev
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:E:/workspaces/Gitxi2852Projects/person-management-system/h2/asset_db_dev
    username: sa
    password:
    driver-class-name: org.h2.Driver
