server:
  port: ${PERSON_SERVICE_PORT:8080}
  servlet:
    context-path: /person-service
spring:
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:file:~/h2/person_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

